version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1001:1001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      DB_DATABASE: student
      DB_USER: root
      DB_PASSWORD: 
      DB_HOST: localhost
    ports:
      - "3000:3000"
